export const demo1 = {
  "patterns": [
    {
      "drums": {
        "kick": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "snare": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "clap": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "hat": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "perc": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "bell": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      },
      "channelSettings": {
        "drums": { "muted": false, "delayTime": "4n", "delayFeedback": 0 },
        "bass": { "wave": "square", "decay": 5, "muted": false },
        "lead": { "wave": "sawtooth", "decay": 5, "muted": false },
        "arp": { "wave": "square", "decay": 5, "muted": false }
      },
      "bass": [
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 }
      ],
      "lead": [
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 }
      ],
      "arp": [
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 }
      ]
    },
    {
      "drums": {
        "kick": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "snare": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "clap": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "hat": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "perc": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "bell": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      },
      "channelSettings": {
        "drums": { "muted": false, "delayTime": "4n", "delayFeedback": 0 },
        "bass": { "wave": "square", "decay": 5, "muted": false },
        "lead": { "wave": "sawtooth", "decay": 5, "muted": false },
        "arp": { "wave": "square", "decay": 5, "muted": false }
      },
      "bass": [
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 }
      ],
      "lead": [
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 },
        { "velocity": 0, "level": 0, "direction": 0, "decay": 5 }
      ],
      "arp": [
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 },
        { "velocity": 0, "level": 0, "chordId": null, "decay": 5 }
      ]
    }
  ],
  "patternEnable": [true, false, false, false],
  "tempo": 120,
  "swing": 0,
  "trackName": "NEW SONG",
  "currentUser": "USER",
  "scaleId": "cmaj",
  "visualizerMode": 5
};
